### ISSUE TITLE
Color Symbol Not Working

### ISSUE THREAD

**Issue by ghost** [HBIDamian/MOTDShuffle#5]
I use latest pmmp 3.0.4

Suggestion: Replace color symbol with &, like easymotd

Error:
 ErrorException: "yaml_parse(): reading error encountered during parsing: invalid leading UTF-8 octet (line 1, column 1)" (EXCEPTION) in "src/pocketmine/utils/Config" at line 155

[Server thread/DEBUG]: #0 (): pocketmine\utils\Utils::errorExceptionHandler(integer 2, string yaml_parse(): reading error encountered during parsing: invalid leading UTF-8 octet (line 1, column 1), string phar:///home/pmmpjason/mainserver/PocketMine-MP.phar/src/pocketmine/utils/Config.php, integer 155, array Array())

**Comment by HBIDamian** [comment]
It works for me, and EVERYONE ELSE. 

```yaml
---
#The Ammount of time that you wish for the MOTD Delay.
#This doesn't make the client's query change,
#this effects the ammount of time the server sends the message.
#Default: 100
MOTD Delay: 100

#Here you can set if you want the shuffle on, or off.
#It is required to use quotations. :D
#Default: "off"
MOTD Shuffle: "on"

#The MOTD Messages.
#You can add to as much as you like! 
#Just make sure you copy it correctly. 
MOTD Message:
    - "§aGreen"
    - "§bBlue"
    - "§cRed"
...
```
